
const target=document.createElement("div");
target.setAttribute("class","container-lg");
target.setAttribute("class","birth")
target.setAttribute("id","priya");
target.innerHTML='<div class="dharshini"><div>'
document.body.append(target);
f1=()=>{
setTimeout(()=>{
 console.log("10")
 target.innerHTML="10"
 f2=()=>{
  setTimeout(()=>{
    console.log("9")
    target.innerHTML="9"
    f3=()=>{
      setTimeout(()=>{
        console.log("8")
        target.innerHTML="8"
        f4=()=>{
          setTimeout(()=>{
            console.log("7")
            target.innerHTML="7"
            f5=()=>{
              setTimeout(()=>{
                console.log("6")
                target.innerHTML="6"
                f6=()=>{
                  setTimeout(()=>{
                    console.log("5")
                    target.innerHTML="5"
                    f7=()=>{
                      setTimeout(()=>{
                        console.log("4")
                        target.innerHTML="4"
                        f8=()=>{
                          setTimeout(()=>{
                            console.log("3")
                            target.innerHTML="3"
                            f9=()=>{
                              setTimeout(()=>{
                                console.log("2")
                                target.innerHTML="2"
                                f10=()=>{
                                  setTimeout(()=>{
                                    console.log("1")
                                    target.innerHTML="1"
                                    f11=()=>{
                                      setTimeout(()=>{
                                        console.log("HAPPY BIRTH DAY")
                                        target.innerHTML="WISH YOU MANY MORE HAPPY RETURNS OF THE DAY (15/12/2022)"
                                        f12=()=>{
                                            setTimeout(()=>{
                                              console.log("P-Precious")
                                              target.innerHTML="P-Precious"
                                              f13=()=>{
                                                setTimeout(()=>{
                                                  console.log("R-Reliable")
                                                  target.innerHTML="R-Reliable"
                                                  f14=()=>{
                                                    setTimeout(()=>{
                                                      console.log("I-Intellectual")
                                                      target.innerHTML="I-Intellectual"
                                                      f15=()=>{
                                                        setTimeout(()=>{
                                                          console.log("Y-Young")
                                                          target.innerHTML="Y-Young"
                                                          f16=()=>{
                                                            setTimeout(()=>{
                                                              console.log("A-Agile")
                                                              target.innerHTML="A-Agile"
                                                              f17=()=>{
                                                                setTimeout(()=>{
                                                                  console.log("D-Delightful")
                                                                  target.innerHTML="D-Delightful"
                                                                  f18=()=>{
                                                                    setTimeout(()=>{
                                                                      console.log("H-Holiness")
                                                                      target.innerHTML="H-Holiness"
                                                                      f19=()=>{
                                                                        setTimeout(()=>{
                                                                          console.log("A-Astute")
                                                                          target.innerHTML="A-Astute"
                                                                          f20=()=>{
                                                                            setTimeout(()=>{
                                                                              console.log("R-Radiance")
                                                                              target.innerHTML="R-Radiance"
                                                                              f21=()=>{
                                                                                setTimeout(()=>{
                                                                                  console.log("S-Staunchness")
                                                                                  target.innerHTML="S-Staunchness"
                                                                                  f22=()=>{
                                                                                    setTimeout(()=>{
                                                                                      console.log("H-Honorable")
                                                                                      target.innerHTML="H-Honorable"
                                                                                      f23=()=>{
                                                                                        setTimeout(()=>{
                                                                                          console.log("I-Ingenious")
                                                                                          target.innerHTML="I-Ingenious"
                                                                                          f24=()=>{
                                                                                            setTimeout(()=>{
                                                                                              console.log("N-Nimble")
                                                                                              target.innerHTML="N-Nimble"
                                                                                              f25=()=>{
                                                                                                setTimeout(()=>{
                                                                                                  console.log("I-Independent")
                                                                                                  target.innerHTML="I-Independent"
                                                                                                  f26=()=>{
                                                                                                    setTimeout(()=>{
                                                                                                      console.log("PRIYA DHARSHINI")
                                                                                                      target.innerHTML='<h1>PRIYA DHARSHINI</h1>'
                                                                                                    },2000)
                                                                                                   }
                                                                                                   f26()
                                                                                                },2000)
                                                                                               }
                                                                                               f25()
                                                                                            },2000)
                                                                                           }
                                                                                           f24()
                                                                                        },2000)
                                                                                       }
                                                                                       f23()
                                                                                    },2000)
                                                                                   }
                                                                                   f22()
                                                                                },2000)
                                                                               }
                                                                               f21()
                                                                            },2000)
                                                                           }
                                                                           f20()
                                                                        },2000)
                                                                       }
                                                                       f19()
                                                                    },2000)
                                                                   }
                                                                   f18()
                                                                },2000)
                                                               }
                                                               f17()
                                                            },2000)
                                                           }
                                                           f16()
                                                        },2000)
                                                       }
                                                       f15()
                                                    },2000)
                                                   }
                                                   f14()
                                                },2000)
                                               }
                                               f13()
                                            },2000)
                                           }
                                           f12()
                                      },2000)
                                     }
                                     f11()
                                  },1000)
                                 }
                                 f10()
                              },1000)
                             }
                             f9()
                          },1000)
                         }
                         f8()
                      },1000)
                     }
                     f7()
                  },1000)
                 }
                 f6()
              },1000)
             }
             f5()
          },1000)
         }
         f4()
      },1000)
     }
     f3()
  },1000)
 }
 f2()
},1000)
}
f1()